### ISSUE TITLE
Subplots not appearing 

### ISSUE THREAD

**Issue by ashleightrinh** [sglyon/PlotlyJS.jl#128]
I have multiple matrices I want to plot in a column. Despite using similar code as in the subplots section it does not appear when I combine them, as shown:
```
p1 = plot(t, g1);
p2 = plot(t, g2);
p3 = plot(t, g3);
[p1, p2, p3]
```
After typing that into the terminal this is the result I get is
```
3-element Array{Plots.Plot{Plots.PlotlyJSBackend},1}:
 Plot{Plots.PlotlyJSBackend() n=6}
 Plot{Plots.PlotlyJSBackend() n=6}
 Plot{Plots.PlotlyJSBackend() n=6}
```
and no plot appears.

I am ```using Plots``` with the ```plotlyjs()``` backend.

**Comment by sglyon** [comment]
Hi @ashleightrinh thanks for coming here!

The issue here is somewhat subtle: the `[p1, p2, p3]` syntax only works when you use PlotlyJS.jl directly. In order to create subplots using Plots.jl you need to tap into the layout functionality offered by Plots.jl  (documentation [here](https://juliaplots.github.io/layouts/)).

Hopefully that helps!

**Comment by ashleightrinh** [comment]
Hi @sglyon thank you for responding so promptly!

I've tried it again using PlotlyJS.jl and now I do get a plot window opening but for some reason all the plots are empty. 

Previously when I tried the layout method offered by Plots.jl it got really complicated since each of my individual data sets (g1, g2, etc.) has 6 lines to plot but they all get plotted in separate subplots rather than each set of data in one subplot each.

Thank you for the help!

**Comment by sglyon** [comment]
Hmm that's odd. Could you please post a sample of the `t` and `g1` variables so I can try it out myself? 

If the data are sensitive you could just create a random data set of the same type as the original objects.

**Comment by ashleightrinh** [comment]
Hi, so the code is quite long so I will attach it as a word document and can be copied and pasted.
[Demo.docx](https://github.com/sglyon/PlotlyJS.jl/files/1143542/Demo.docx)
It's a function so I don't know how to extract just ```t``` and ```g1```.

**Comment by ashleightrinh** [comment]
Sorry, I thought ```close and comment``` meant close the window.

**Comment by sglyon** [comment]
No problem.

I don't have word on my computer.

I should be able to tell everything that I need just from the types of `t` and `g1`

Could you instead just post the types of these two variables. You can use the `typeof` function to get that info

**Comment by ashleightrinh** [comment]
Ok, so ```g1``` is an ```Array{Float64,2}``` and ```t``` is an ```Array{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},1}```.

**Comment by sglyon** [comment]
Hey @ashleightrinh thank you for that.

It turns out this was an issue within PlotlyJS that I've just fixed with the previous commit.

If you do `Pkg.checkout("PlotlyJS")` and then try your plotting code again it should work now.

Today I will tag a new release with METADATA.jl. This means if you wait a few hours you can do `Pkg.update()` instead and your example will work with the released version of this package.

I'll try to remember to post here when METADATA is updated.

**Comment by sglyon** [comment]
The METADATA PR has been merged: https://github.com/JuliaLang/METADATA.jl/pull/10250#event-1163036600

You can now just do `Pkg.update()` to get the version of PlotlyJS.jl where you could should work. If it doesn't work after updating please respond here!
