### ISSUE TITLE
WebGL / Max Dataset Size/Data Point Quantity?

### ISSUE THREAD

**Issue by versipellis** [sglyon/PlotlyJS.jl#260]
One of the strengths of PlotlyJS is being able to render millions of datapoints using WebGL:
* https://plot.ly/r/webgl-vs-svg-million-points/
* https://plot.ly/benchmarks/

Is there an approximate dataset size or data point quantity that PlotlyJS.jl is performant up till, or a way to tell PlotlyJS to use WebGL for rendering?

**Comment by sglyon** [comment]
You can have PlotlyJS.jl use WebGL by using a `gl` suffixed trace name.

For example, `scattergl` instead of `scatter`, or `heatmapgl` instead of `heatmap`.

The main bottleneck for PlotlyJS.jl will be IO related as we JSON encode all the data on the julia side, send over to javascript, then JSON.parse from within javascript. If we had a more efficient means of transporting data then the bottleneck would again be on  plotly.js

**Comment by versipellis** [comment]
That's what I suspected as much too, since the stacktrace was throwing JSON issues. Just tested it with `scattergl` and its similar situation :( Thanks a ton!
