### ISSUE TITLE
Feature request: DateTime support

### ISSUE THREAD

**Issue by amellnik** [sglyon/PlotlyJS.jl#87]
I think it's not a high priority for most of us since `Date`s work fine, but it would be nice to have.  Right now `DateTime`s don't throw an error, but are treated as categorical strings.

**Comment by spencerlyon2** [comment]
Hey @amellnik I actually ran into this the other day.

The issue is that julia exports DateTime to string like this:

```
julia> now()
2016-10-13T07:20:58.166
```

whereas plotly.js expects the same, but without the T: `2016-10-13 07:20:58.166`.

I asked the plotly.js guys if they could support the version with the `T, and they made it seem like it would be a bigger issue than "just allowing it". It's too bad because the version with the T is the [official ISO 8601 specification](https://en.wikipedia.org/wiki/ISO_8601).

There are two things I could think of on this side:

1. Add `JSON.lower(d::DateTime)` that doesn't include the T. I don't really like this because we are extending someone else's method for someone else's type.
2. Add a processing layer just before sending to JSON that would look for DateTime and convert it to the string we need. I've avoided this because I haven't wanted there to be data transformation between Julia and plotly.js.

If anyone has other ideas, I'd love to hear them!

**Comment by tbreloff** [comment]
Not a solution of course, but you can plot DateTime through Plots. It uses
a type recipe which converts to numbers and adds a special tick formatter
to the axis. You'll need master until I tag a new version (today maybe?)

**Comment by sglyon** [comment]
I believe this is fixed in the latest plotly.js releases from upstream.

If someone finds otherwise please reopen or make a comment so I can reopen

**Comment by kafisatz** [comment]
I currently get the error below when trying to use a datetime vector as x axis.
Is this supposed to work? 

```
julia> aPlot=PlotlyJS.plot(df.datetime,df[!,varsOfInterest[varNum]],layout,size=plotsize,ticks = :native,dpi=200,show=true,xlabel="Time",ylabel=string(varsOfInterest[varNum]))
ERROR: MethodError: no method matching Plot(::Array{Dates.DateTime,1}, ::Array{Float64,1}, ::Layout{Dict{Symbol,Any}}; size=(2000, 800), ticks=:native, dpi=200, show=true, xlabel="Time", ylabel="TA [°C]")
Closest candidates are:
  Plot(::AbstractArray{T<:Union{Date, AbstractString, Number, Symbol},1}, ::AbstractArray{T,1} where T, ::Layout; kind, style, kwargs...) where T<:Union{Date, AbstractString, Number, Symbol} at C:\Users\bernhard.konig\.julia\packages\PlotlyBase\qL4g1\src\convenience_api.jl:20
  Plot(::AbstractArray{T<:Union{Date, AbstractString, Number, Symbol},1}, ::AbstractArray{T,1} where T) where T<:Union{Date, AbstractString, Number, Symbol} at C:\Users\bernhard.konig\.julia\packages\PlotlyBase\qL4g1\src\convenience_api.jl:20 got unsupported keyword arguments "size", "ticks", "dpi", "show", "xlabel", "ylabel"
  Plot(::AbstractArray{T<:Union{Date, AbstractString, Number, Symbol},1}, ::AbstractArray{T,2} where T, ::Layout; style, kwargs...) where T<:Union{Date, AbstractString, Number, Symbol} at C:\Users\bernhard.konig\.julia\packages\PlotlyBase\qL4g1\src\convenience_api.jl:25
  ...
Stacktrace:
 [1] #plot#6(::Dict{Any,Any}, ::Base.Iterators.Pairs{Symbol,Any,NTuple{6,Symbol},NamedTuple{(:size, :ticks, :dpi, :show, :xlabel, :ylabel),Tuple{Tuple{Int64,Int64},Symbol,Int64,Bool,String,String}}}, ::Function, ::Array{Dates.DateTime,1}, ::Vararg{Any,N} where N) at C:\Users\bernhard.konig\.julia\packages\PlotlyJS\I8Gki\src\display.jl:143
 [2] (::getfield(PlotlyJS, Symbol("#kw##plot")))(::NamedTuple{(:size, :ticks, :dpi, :show, :xlabel, :ylabel),Tuple{Tuple{Int64,Int64},Symbol,Int64,Bool,String,String}}, ::typeof(plot), ::Array{Dates.DateTime,1}, ::Vararg{Any,N} where N) at .\none:0
 [3] top-level scope at none:0

julia> 

julia> df.datetime
4560-element Array{Dates.DateTime,1}:
 2019-09-27T16:33:24
 2019-09-27T16:34:24
 2019-09-27T16:35:24
 2019-09-27T16:36:24
 2019-09-27T16:37:24
 2019-09-27T16:38:24
 2019-09-27T16:39:24

```

**Comment by sglyon** [comment]
Hey @kafisatz I believe the issue comes from the definition of this internal type `_Scalar`: https://github.com/sglyon/PlotlyBase.jl/blob/e212bd8242121d98077ce7bfae3c76f16ee75b40/src/traces_layouts.jl#L59

If we were to add DateTime to that list I think the issue would be fixed.

@kafisatz are you willing to make this change, test this out using your data, and submit a pull request over in PlotlyBase (the repo where that union us defined)?

**Comment by kafisatz** [comment]
I can confirm that this change does the trick for my data.

**Comment by sglyon** [comment]
Excellent! Thank you for making the pull request
